# ==============================================================================
# Generated by qmake (2.01a) (Qt 4.6.2) on: lun 26. apr 22:15:44 2010
# This file is generated by qmake and should not be modified by the
# user.
#  Name        : Makefile_0xE8d4cdf3.mk
#  Part of     : testudp
#  Description : This file is used to call necessary targets on wrapper makefile
#                during normal Symbian build process.
#  Version     : 
#
# ==============================================================================



MAKE = make

VISUAL_CFG = RELEASE
ifeq "$(CFG)" "UDEB"
VISUAL_CFG = DEBUG
endif

do_nothing :
	@rem do_nothing

MAKMAKE: create_temps pre_targetdeps store_build

LIB: create_temps pre_targetdeps store_build

BLD: create_temps pre_targetdeps store_build

ifeq "$(PLATFORM)" "WINSCW"
CLEAN: extension_clean winscw_deployment_clean
else
CLEAN: extension_clean
endif

CLEANLIB: do_nothing

RESOURCE: do_nothing

FREEZE: do_nothing

SAVESPACE: do_nothing

RELEASABLES: do_nothing

ifeq "$(PLATFORM)" "WINSCW"
FINAL: finalize winscw_deployment
else
FINAL: finalize
endif

pre_targetdeps : c:\Mobivu\test udp\testudp\Makefile
	-$(MAKE) -f "c:\Mobivu\test udp\testudp\Makefile" pre_targetdeps QT_SIS_TARGET=$(VISUAL_CFG)-$(PLATFORM)

create_temps : c:\Mobivu\test udp\testudp\Makefile
	-$(MAKE) -f "c:\Mobivu\test udp\testudp\Makefile" create_temps QT_SIS_TARGET=$(VISUAL_CFG)-$(PLATFORM)

extension_clean : c:\Mobivu\test udp\testudp\Makefile
	-$(MAKE) -f "c:\Mobivu\test udp\testudp\Makefile" extension_clean QT_SIS_TARGET=$(VISUAL_CFG)-$(PLATFORM)

finalize : c:\Mobivu\test udp\testudp\Makefile
	-$(MAKE) -f "c:\Mobivu\test udp\testudp\Makefile" finalize QT_SIS_TARGET=$(VISUAL_CFG)-$(PLATFORM)

winscw_deployment_clean : c:\Mobivu\test udp\testudp\Makefile
	-$(MAKE) -f "c:\Mobivu\test udp\testudp\Makefile" winscw_deployment_clean QT_SIS_TARGET=$(VISUAL_CFG)-$(PLATFORM)

winscw_deployment : c:\Mobivu\test udp\testudp\Makefile
	-$(MAKE) -f "c:\Mobivu\test udp\testudp\Makefile" winscw_deployment QT_SIS_TARGET=$(VISUAL_CFG)-$(PLATFORM)

store_build : c:\Mobivu\test udp\testudp\Makefile
	-$(MAKE) -f "c:\Mobivu\test udp\testudp\Makefile" store_build QT_SIS_TARGET=$(VISUAL_CFG)-$(PLATFORM)


